### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by luizbills** [luizbills/v#1]
## Instructions

- choose a filter [here](https://github.com/luizbills/v/blob/master/src/filters)
- create a file with name `{filter}.spec.php`in `spec/filters` directory and put your tests there. ([example](https://github.com/luizbills/v/blob/master/spec/filters/capitalize.spec.php))

**Comment by kimyvgy** [comment]
Hi, I see it from Hacktoberfest. I would like to take this.

**Comment by luizbills** [comment]
go ahead!
