### ISSUE TITLE
add `tag` filter

### ISSUE THREAD

**Issue by luizbills** [luizbills/v#6]
`tag(name, class, id)` filter should wrap the value into a tag

```php
echo v( 'My Title', 'tag(h1, "my-id", "my-class")', 'raw' );
// => <h1 id="my-id" class="my-class">My Title</h1>
```

**Comment by liloo2040** [comment]
Hello! I would be happy to contribute to your project!

**Comment by luizbills** [comment]
Go ahead. If you need help, let me know.

**Comment by liloo2040** [comment]
Thanks! I would like to know, once I've installed the project, how can I check if my code works ?

**Comment by luizbills** [comment]
- create a directory for your tests
- run in terminal: `composer require luizbills/v --prefer-dist`
- create a file `index.php` and test (read the README.md to learn how)
- now, access via webserve or run: `php index.php`

**Comment by liloo2040** [comment]
Thank you!

**Comment by liloo2040** [comment]
Hi! Unfortunately, I can't help you with this issue.

**Comment by luizbills** [comment]
@liloo2040 no problem

**Comment by dannyverp** [comment]
I'll get to work on this :)

**Comment by dannyverp** [comment]
Your example mixes up the id and the class. Should class or id come first? :)
